### PR TITLE
Fix bug in ActionList lazy loading

### LINKED ISSUE #969: Lazy loading bug when list changes
When a list changes, it does not trigger a re-load of the visible objects until they're scrolled out of view and back again, which may not be possible if the list is not long enough.

Steps to reproduce:

1. Navigate to the action list
2. Wait for participants to load into visible action items
3. Click to show past actions

Expected results: Past actions should show and participants for visible actions should load
Actual results: Past actions show, but participants do not load

### PR DESCRIPTION
**Pull request by richardolsson**
Fixes #969 

(See issue ticket for details)

### CODE REVIEW

**Comment by richardolsson** [comment]
I'm taking a long shot that you'll be able to review this today, @olleolleolle, before I start preparing the release. Let me know if you can't. 😄

File: src/components/lists/items/ActionListItem.jsx [hunk 1]
```diff
@@ -103,16 +103,26 @@ export default class ActionListItem extends React.Component {
...
+    componentDidMount() {
+        if (this.props.inView) {
+            this.loadSubData();
+        }
+    }
+
+    loadSubData() {
+        const action = this.props.data;
+        const participants = this.props.participants;
+        const responses = this.props.responses;
```
Comment (olleolleolle) [inline src/components/lists/items/ActionListItem.jsx]: Is destructuring assignment available here?

`const { action, participants, responses } = this.props;`

Comment (richardolsson) [reply src/components/lists/items/ActionListItem.jsx]: It should work, but it's something we haven't been using (consistently) before. I really think we need a general code style overhaul at some point seeing how javascript has evolved since this project started (almost exactly!) four years ago. That's the kind of work that I have planned for late 2019, although I guess it makes sense to start implementing it little by little already.

Comment (olleolleolle) [reply src/components/lists/items/ActionListItem.jsx]: (Thanks also for spotting the bug in my shoddy example!)
