### PR TITLE
Fix SurveySubmission filtering bug

### LINKED ISSUE #1040: Filtering SurveySubmissions on linking status not working
When filtering SurveySubmissions on linking status the list should only contain results matching current filter.

Example: Filtering on linked submissions
Expected behavior: Returns linked submissions
Actual behavior: Returns unlinked submissions

### PR DESCRIPTION
**Pull request by martinajsongren**
Fixes issue where filtering on linked/unlinked SurveySubmission always return unlinked submissions.
Closes #1040

### CODE REVIEW

File: src/actions/surveySubmission.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ export function retrieveSurveySubmissions(surveyId = null, linked = null, page =
         let promise;
 
         if (linked !== null) {
-            linked = linked? ((filters.linked == 'linked')? 1 : 0) : null;
+            linked = linked? ((linked == 'linked')? 1 : 0) : null;
```
Comment (olleolleolle) [inline src/actions/surveySubmission.js]: As a formatting comment, when I write ternary conditional statements, I usually place the question mark whitespace-separated. 

The hope then is that the reader can separate the parts of the statement.

Comment (martinajsongren) [reply src/actions/surveySubmission.js]: I agree with this, but totally missed it when fixing this issue. Thanks for pointing it out! Will commit change asap :)
