### PR TITLE
bugfix/smart filter defaults

### LINKED ISSUE #727: Call history filter update issue
Data does not update properly when changing the settings of a `call_history` query filter. Steps to reproduce:

1. Create a new query with a tag filter minus a call history filter with the following settings: "called during a certain assignment", any assignment, "whenever"
2. Save and close the query settings
3. Open settings again and change the first setting to "reached during a certain assignment"
4. Save and close the settings again
5. Open settings again

Expected results: The first setting should now have been changed
Actual results: The first setting has gone back to "called during a certain assignment"

Workaround: In step 3, also change another setting (and change it back again).

### PR DESCRIPTION
**Pull request by Bagera**
Fixes #727 and #590

### CODE REVIEW

File: src/components/filters/SurveyOptionFilter.jsx [hunk 1]
```diff
@@ -169,6 +169,20 @@ export default class SurveyOptionFilter extends FilterBase {
     onChangeSimpleField(name, value) {
         let state = {};
         state[name] = value;
+
```
Comment (richardolsson) [inline src/components/filters/SurveyOptionFilter.jsx]: Superfluous whitespace on this line.

File: src/components/filters/SurveyOptionFilter.jsx [hunk 2]
```diff
@@ -158,7 +158,7 @@ export default class SurveyOptionFilter extends FilterBase {
                 }
             }
         }
-
+
```
Comment (richardolsson) [inline src/components/filters/SurveyOptionFilter.jsx]: Superfluous whitespace on this line.

**Comment by richardolsson** [comment]
The issue wasn't automatically closed when merging this, probably because the opening comment didn't explicitly say "Fixes #590". Please put "Fixes" directives on separate lines per issue for future PRs. :)
