### PR TITLE
Fix action import bug caused by CSV import feature

### LINKED ISSUE #1079: Action import fails in recent versions
The CSV import feature added recently has introduced a bug in the campaign/action import, which now receives a promise but is expecting it to be a resolved object.

Steps to reproduce
1. Open the action import pane from the calendar root pane
2. Drag any Excel file to the drop zone

Expected results: File should be parsed and either show a list or some error message
Actual results: Nothing happens in UI, error is thrown in console:

```
main.js:47 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at actionImport (main.js:47)
    at main.js:66
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.dispatch (main.js:36)
    at e (<anonymous>:1:40553)
    at main.js:47
    at main.js:47
    at main.js:66
```

This seems to be because src/utils/importer.js now returns a promise and not a resolved "table set" object.

Proposed fix: Make sure that the `parseActionImportFile()` action handles the returned promise from `parseWorkbook()` instead of incorrectly assuming it's a plain object.

### PR DESCRIPTION
**Pull request by niklasva82**
Resolves #1079

### CODE REVIEW

File: src/actions/actionImport.js [hunk 1]
```diff
@@ -10,8 +10,9 @@ export function parseActionImportFile(file) {
 
         reader.onload = e => {
             // TODO: Check type and support CSV as well
-            let tableSet = parseWorkbook(e.target.result);
-            resolve({ tableSet });
+            parseWorkbook(e.target.result)
+                .then(tableSet => resolve({ tableSet }))
```
Comment (olleolleolle) [inline src/actions/actionImport.js:14]: If you passed the bare `tableSet`, not wrapped in a `{ tableSet: tableSet }` literal, could you do without the  actionImport.js change, then?

**Review by olleolleolle — COMMENTED** [review]
I looked at the code, briefly, 👏 and yay it looks like it fixes that Issue on sight, but I wonder if it is possible to make the change even smaller.

File: src/actions/actionImport.js (hunk 1 above)
Comment (richardolsson) [reply src/actions/actionImport.js:14]: @olleolleolle The `parseWorkbook()` function is also used [elsewhere](https://github.com/zetkin/organize.zetk.in/blob/master/src/actions/importer.js), where it's expected to return an object like this. If I understand your suggestion correctly, that would break (or require more changes). Am I right?

Comment (olleolleolle) [reply src/actions/actionImport.js:14]: My suggestion came from: the _other_ change in this PR, is that a follow-up, un-related fix to this repair?

Comment (niklasva82) [reply src/actions/actionImport.js:14]: action/actionImport is not used elsewhere to my knowledge, I suppose I could just resolve(tableset), then there's no need to change store/actionImport and it would actually be better from a compatibility standpoint if it was used elsewhere for some odd reason.

Comment (olleolleolle) [reply src/actions/actionImport.js:14]: Thanks for the follow-up questions, Richard. And, I hope this comes across as my trying to be understood, rather than anything else. All this is Good Work.

Comment (richardolsson) [reply src/actions/actionImport.js:14]: Ah, I get it now. I was confused by the naming i guess. The first use of `tableSet` here, i.e. the argument in the function is not actually the table-set, but an object containing the field `tableSet` I believe? So maybe a better name would be `data` or `workbook` or something, along with the change suggested by Olle?

I'll let you decide @niklasva82 since I might be mistaken. Do you want to update the PR before I review?

Comment (niklasva82) [reply src/actions/actionImport.js]: @richardolsson True regarding the naming. I fixed that as well now.

**Review by olleolleolle — APPROVED** [review]
❤️ 💯

**Review by richardolsson — COMMENTED** [review]
Thanks for simplifying, and thanks to @olleolleolle for keen eyes and suggestions!

The code looks good. I will try running it as well before merging but this should be fine!

**Review by richardolsson — APPROVED** [review]
Tested and found to be working!
