### PR TITLE
fixed bug where allowed edit person tag title to be empty

### LINKED ISSUE #723: Possible to create tag with empty string
1. Edit an existing tag
2. Clear the tag name
3. Save

Expected result: empty string not accepted, OR tag is deleted
Actual result: tag with empty string is created

screen shot 2017-12-12 at 15 02 48

### PR DESCRIPTION
**Pull request by sam-mcmurray**
fixes #723

### CODE REVIEW

File: src/components/panes/EditPersonTagPane.jsx [hunk 1]
```diff
@@ -57,11 +69,15 @@ export default class EditPersonTagPane extends PaneBase {
...
 
     renderPaneFooter(data) {
+        if (this.state.shouldShowButton) {
         return (
             <Button className="EditPersonTagPane-saveButton"
                 labelMsg="panes.editPersonTag.saveButton"
                 onClick={ this.onSubmit.bind(this) }/>
         );
+        } else {
+    return null;
```
Comment (richardolsson) [inline src/components/panes/EditPersonTagPane.jsx:79]: Poor indentation.

File: src/components/panes/EditPersonTagPane.jsx [hunk 2]
```diff
@@ -73,4 +89,10 @@ export default class EditPersonTagPane extends PaneBase {
         this.props.dispatch(updatePersonTag(tagId, values));
         this.closePane();
     }
+
+    onValueChange(name, value) {
+        if (name === "title") {
+            this.setState({ shouldShowButton: Boolean(value) })
```
Comment (richardolsson) [inline src/components/panes/EditPersonTagPane.jsx:95]: Nice and simple!

Another way of doing `Boolean(value)` is to do `!!value`, which you will find in other places of this codebase.

**Review by richardolsson — CHANGES_REQUESTED** [review]
Nice work! Thanks for this submission and congratulations on your first Zetkin pull request! 🎉 

This is working as expected and save for a tiny style issue the code looks great too.

Would it be possible for you to implement the same approach to the `AddPersonTagPane`, which seems to have the same issue?

**Review by richardolsson — APPROVED** [review]
Nice work! 

Quality work
