### PR TITLE
Fix validation error

### LINKED ISSUE #1219: Error when validating import
Reported by a user. Seems to be a case of phone numbers which have been stored as number (not text) in the Excel file.

```
ConfirmImportPane.jsx:145 Uncaught TypeError: row.values[colidx].replace is not a function
    at ConfirmImportPane.value (ConfirmImportPane.jsx:145)
    at ConfirmImportPane.value (ConfirmImportPane.jsx:233)
    at ConfirmImportPane.value (PaneBase.jsx:47)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:819)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:359)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:368)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:255)
value	@	ConfirmImportPane.jsx:145
value	@	ConfirmImportPane.jsx:233
value	@	PaneBase.jsx:47
_renderValidatedComponentWithoutOwnerOrContext	@	ReactCompositeComponent.js:796
_renderValidatedComponent	@	ReactCompositeComponent.js:819
performInitialMount	@	ReactCompositeComponent.js:359
mountComponent	@	ReactCompositeComponent.js:255
mountComponent	@	ReactReconciler.js:43
performInitialMount	@	ReactCompositeComponent.js:368
mountComponent	@	ReactCompositeComponent.js:255
mountComponent	@	ReactReconciler.js:43
performInitialMount	@	ReactCompositeComponent.js:368
mountComponent	@	ReactCompositeComponent.js:255
mountComponent	@	ReactReconciler.js:43
updateChildren	@	ReactChildReconciler.js:119
_reconcilerUpdateChildren	@	ReactMultiChild.js:209
_updateChildren	@	ReactMultiChild.js:308
updateChildren	@	ReactMultiChild.js:295
_updateDOMChildren	@	ReactDOMComponent.js:944
updateComponent	@	ReactDOMComponent.js:758
receiveComponent	@	ReactDOMComponent.js:720
receiveComponent	@	ReactReconciler.js:122
updateChildren	@	ReactChildReconciler.js:107
_reconcilerUpdateChildren	@	ReactMultiChild.js:209
_updateChildren	@	ReactMultiChild.js:308
updateChildren	@	ReactMultiChild.js:295
_updateDOMChildren	@	ReactDOMComponent.js:944
updateComponent	@	ReactDOMComponent.js:758
receiveComponent	@	ReactDOMComponent.js:720
receiveComponent	@	ReactReconciler.js:122
Show 72 more frames

```

### PR DESCRIPTION
**Pull request by niklasva82**
Fixes #1219 by converting any non-string to string in import validation.

I cannot reproduce the error however, so this is a highly theoretical fix.

### CODE REVIEW

File: src/components/panes/ConfirmImportPane.jsx [hunk 1]
```diff
@@ -109,6 +109,10 @@ export default class ConfirmImportPane extends PaneBase {
             for (let colidx = 0; colidx < columns.length; colidx++) {
                 const column = this.getFieldID(columns[colidx]);
                 if(row.values[colidx]) {
+                    if(typeof(row.values[colidx]) !== 'string') {
+                        row.values[colidx] = str(row.values[colidx]);
```
Comment (richardolsson) [inline src/components/panes/ConfirmImportPane.jsx:113]: What is `str()`?

Comment (niklasva82) [reply src/components/panes/ConfirmImportPane.jsx]: Fixed this typo. It appears to work but I still haven't been able to reproduce the error.

**Review by richardolsson — APPROVED** [review]
Looking good now! I was able to reproduce the error using a user-submitted file, and confirm that the change fixes it.

Nice shooting in the dark! 💥 🔫
